version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

services:


  dev:
    <<: *base-dev
    image: salimfadhley/python_playground:latest
    build:
      context: .
      target: python
    volumes:
      - ./src:/src
      - .:/project
    working_dir: "/home/sal/workspace/uk_improv_guide"
    entrypoint: ["/usr/local/bin/python", "manage.py", "runserver"]
    ports:
      - "8000:8000"

  python:
    <<: *base-dev
    image: salimfadhley/python_playground:latest
    build:
      context: .
      target: python
    volumes:
      - ./src:/src
      - .:/project
    entrypoint: ["/usr/local/bin/python"]

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: improv
      MYSQL_USER: improv
      MYSQL_PASSWORD: changeme
    volumes:
      - "./data/mysql:/var/lib/mysql"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: "db"




