version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-base-database: &base-database
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}

x-base-image: &base-image
  image: "salimfadhley/uk_improv_guide:${IMPROV_GUIDE_VERSION}"
  build:
    context: .
    target: uk_improv_guide

services:

  dev:
    <<: *base-dev
    <<: *base-image

    volumes:
      - ./src:/src
      - ./static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start.sh"]
    expose:
      - "80"
    depends_on:
      - db
    environment:
      <<: *base-database
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal

  prod:
    <<: *base-dev
    <<: *base-image

    volumes:
      - ./src:/src
      - ./static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["gunicorn", "--bind=0.0.0.0:80", "uk_improv_guide.wsgi"]
    expose:
      - 80
    depends_on:
      - db
    environment:
      <<: *base-database
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal



  python:
    <<: *base-image
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *base-database
    networks:
      - internal

  db:
    <<: *base-dev
    image: postgres:10.9
    container_name: "postgres"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: '5432'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal

  adminer:
    image: adminer:4.7.1
    container_name: "dev_adminer"
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - prod



volumes:
  postgres_data:


networks:
  internal: