version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-base-database: &base-database
  DATABASE_NAME: ${POSTGRES_NAME}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  DATABASE_HOST: 'db'
  DATABASE_PORT: ${POSTGRES_PORT}


services:

  dev:
    <<: *base-dev
    image: salimfadhley/uk_improv_guide:${UK_IMPROV_GUIDE_VERSION}
    build:
      context: .
      target: uk_improv_guide
    volumes:
      - ./src:/src
      - ./static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start.sh"]
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      <<: *base-database
      SITE_PORT: ${SITE_PORT}



  python:
    image: salimfadhley/uk_improv_guide:${UK_IMPROV_GUIDE_VERSION}
    build:
      context: .
      target: uk_improv_guide
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *base-database

  db:
    <<: *base-dev
    image: postgres
#    command: --help
#    entrypoint: "/bin/sh"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PORT: '5432'

  adminer:
    image: adminer:4.7.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db


volumes:
  postgres_data:



