version: '3.7'

x-base-dev: &base-dev
  restart: on-failure


x-base-database: &base-database
  DATABASE_NAME: 'improv'
  DATABASE_USER: 'improv'
  DATABASE_PASSWORD: 'changeme'
  DATABASE_HOST: 'db'
  DATABASE_PORT: '3306'
  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

services:


  dev:
    <<: *base-dev
    image: salimfadhley/uk_improv_guide:${UK_IMPROV_GUIDE_VERSION}
    build:
      context: .
      target: uk_improv_guide
    volumes:
      - ./src:/src
      - ./static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      <<: *base-database

  python:
    <<: *base-dev
    image: salimfadhley/uk_improv_guide:${UK_IMPROV_GUIDE_VERSION}
    build:
      context: .
      target: uk_improv_guide
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *base-database

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'


  adminer:
    image: adminer:4.7.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db

#  nginx:
#    image: ngnix:latest
#    restart: always
#    ports:
#      - "7999:80"
#    volumes:
#      - ./static:/usr/share/nginx/html:ro

volumes:
  mysql_data:



