version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-base-database: &base-database
  DATABASE_NAME: ${POSTGRES_NAME}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  DATABASE_HOST: 'db'
  DATABASE_PORT: ${POSTGRES_PORT}

x-base-image: &base-image
  image: salimfadhley/uk_improv_guide:0.1.4

services:

  dev:
    <<: *base-dev
    <<: *base-image
    build:
      context: .
      target: uk_improv_guide
    volumes:
      - ./src:/src
      - ./static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start.sh"]
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      <<: *base-database
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal



  python:
    <<: *base-image
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *base-database
    networks:
      - internal

  db:
    <<: *base-dev
    image: postgres:11.4
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PORT: '5432'
    secrets:
      - postgres_password
    networks:
      - internal

  adminer:
    image: adminer:4.7.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db
    networks:
      - internal


volumes:
  postgres_data:

secrets:
  postgres_password:
    external: true

networks:
  internal: