version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

services:

  python:
    <<: *base-dev
    image: salimfadhley/python_playground:latest
    build:
      context: .
      target: python
    volumes:
      - ./src:/src
      - .:/project



