version: '3.7'

services:
  site:
    restart: on-failure
    image: salimfadhley/uk_improv_guide:${UK_IMPROV_GUIDE_VERSION}
    build:
      context: .
      target: uk_improv_guide
    volumes:
      - ./src:/src
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start.sh"]
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
    depends_on:
      - db

volumes:
  mysql_data:



