version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-base-database: &base-database
  DATABASE_NAME: ${POSTGRES_NAME}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  DATABASE_HOST: 'db'
  DATABASE_PORT: ${POSTGRES_PORT}


services:
  site:
    <<: *base-dev
    image: salimfadhley/uk_improv_guide:${UK_IMPROV_GUIDE_VERSION}
    volumes:
      - ~/data/static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start.sh"]
    ports:
      - "80:${SITE_PORT}"
    depends_on:
      - db
    environment:
      <<: *base-database
      SITE_PORT: ${SITE_PORT}

  db:
    <<: *base-dev
    image: postgres
    #    command: --help
    #    entrypoint: "/bin/sh"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PORT: '5432'



volumes:
  postgres_data:



